# Generated by Django 2.2 on 2019-05-10 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('App_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clock_in',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_in', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_users.Users')),
            ],
        ),
        migrations.CreateModel(
            name='Clock_out',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_out', models.DateTimeField(auto_now=True)),
                ('time_in_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='clocking_system.Clock_in')),
            ],
        ),
    ]
