# Generated by Django 2.2.1 on 2019-05-16 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('App_users', '0001_initial'),
        ('clocking_system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vibration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.FloatField(default=0.0, max_length=200)),
                ('vibration_Ve', models.FloatField(default=0.0)),
                ('clock_out_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='clocking_system.Clock_out')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_users.Users')),
            ],
        ),
    ]
